export enum WidgetType {
  barchart = 'barchart',
  button = 'button',
  candle_stick_chart = 'candle_stick_chart',
  dynamic_barchart = 'dynamic_barchart',
  gaugechart = 'gaugechart',
  geo_chart = 'geo_chart',
  linechart = 'linechart',
  other_charts = 'other_charts',
  scatter_chart = 'scatter_chart',
  speed_three_d = 'speed_three_d',
  splitter = 'splitter',
  sunburst_chart = 'sunburst_chart',
  three_d = 'three_d',
  three_dchart = 'three_dchart',
  tree_map_chart = 'tree_map_chart',
}

export enum MessageSource {
  // The Message is sent from WebView to the React
  WebView,
  // The Message is sent from React to the WebView
  Hulk
}

export enum BaseMessagePurpose {
  // === 3-way handshake ===
  initialize,
  setWidgetBaseConfig,
  setWidgetDefaultData,

  updateWidgetData,
  triggerAction,
}


export enum BaseTriggerActions {
  onClick = 'onClick',
  onMouseEnter = 'onMouseEnter',
  onMouseLeave = 'onMouseLeave',
  onMouseMove = 'onMouseMove',
  onMouseOver = 'onMouseOver',
  onMouseOut = 'onMouseOut',
  onFocus = 'onFocus',
  onBlur = 'onBlur',
  onKeyDown = 'onKeyDown',
  onKeyPress = 'onKeyPress',
  onKeyUp = 'onKeyUp',
  onChange = 'onChange',
  onInput = 'onInput',
  onSubmit = 'onSubmit',
  onReset = 'onReset',
  onScroll = 'onScroll',
  onWheel = 'onWheel',
  onDrag = 'onDrag',
  onDragStart = 'onDragStart',
  onDragEnd = 'onDragEnd',
  onDragEnter = 'onDragEnter',
  onDragLeave = 'onDragLeave',
  onDragOver = 'onDragOver',
  onDragDrop = 'onDragDrop',
  onTouchStart = 'onTouchStart',
  onTouchMove = 'onTouchMove',
  onTouchEnd = 'onTouchEnd',
  onTouchCancel = 'onTouchCancel',
  onCopy = 'onCopy',
  onCut = 'onCut',
  onPaste = 'onPaste',
  onSelect = 'onSelect',
  onContextMenu = 'onContextMenu',
  onPlay = 'onPlay',
  onPause = 'onPause',
  onEnded = 'onEnded',
  onTimeUpdate = 'onTimeUpdate',
  onVolumeChange = 'onVolumeChange',
  onSeeking = 'onSeeking',
  onSeeked = 'onSeeked',
  onRateChange = 'onRateChange',
  onDurationChange = 'onDurationChange',
  onLoadedMetadata = 'onLoadedMetadata',
  onLoadedData = 'onLoadedData',
  onCanPlay = 'onCanPlay',
  onCanPlayThrough = 'onCanPlayThrough',
  onWaiting = 'onWaiting',
  onStalled = 'onStalled',
  onSuspend = 'onSuspend',
  onAbort = 'onAbort',
  onError = 'onError',
  onLoadStart = 'onLoadStart',
  onProgress = 'onProgress',
  onLoad = 'onLoad',
  onTransitionEnd = 'onTransitionEnd',
  onAnimationStart = 'onAnimationStart',
  onAnimationEnd = 'onAnimationEnd',
  onAnimationIteration = 'onAnimationIteration',
  onAnimationCancel = 'onAnimationCancel',
}